[workspace]
members = [
    "forlorn",
    "webhook",
    "storage",
]

resolver = "2"

[workspace.dependencies]
reqwest = { version = "0.12.19", features = ["json"] }
serde = "1.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
